### ISSUE TITLE
Crash when casting Golem while flying

### ISSUE THREAD

**Issue by DracoC2M** [WinDanesz/WizardryGolems#3]
Hi. I found a little bug. When you cast an Golem while in the air in any way, the game will crash.

`java.lang.NullPointerException: Ticking player
	at com.windanesz.wizardrygolems.spell.EarthGolemancy.spawnGolem(EarthGolemancy.java:233)
	at com.windanesz.wizardrygolems.spell.EarthGolemancy.spawnMinions(EarthGolemancy.java:182)
	at com.windanesz.wizardrygolems.spell.EarthGolemancy.cast(EarthGolemancy.java:60)
	at electroblob.wizardry.item.ItemWand.cast(ItemWand.java:478)
	at electroblob.wizardry.item.ItemWand.onUsingTick(ItemWand.java:442)
	at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2678)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2097)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
`

**Comment by Serega007RU** [comment]
Same problem

**Comment by Ratatatang** [comment]
It's connected to wizardry fates as far as I can tell, the golemancy spells outright wouldnt summon anything even with the correct gear and discipline. After removing fates it works while flying and correctly summons the golems.

**Comment by WinDanesz** [comment]
Fixed by v1.3.0
